### PR TITLE
Add optional api key argument to client

### PR DESCRIPTION
**Pull request by cc7768**

### CODE REVIEW

**Comment by cc7768** [comment]
Resolves https://github.com/valorumdata/cmdc.py/issues/4

**Comment by sglyon** [comment]
Looks great thanks!

**Comment by TomGoBravo** [comment]
Are you sure this does what you intend? From a glance it looks like the code before this change depends on `if self.key` in `__init__` causing `self.sess.headers.update({"apikey": x})` to be run, which won't happen when self._key is not None.

**Comment by sglyon** [comment]
Good catch! fixing now

**Comment by sglyon** [comment]
Should be fixed on master!

(we'll get a basic test suite in place for stuff like this soon!)

**Pull request merged**
